# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ben Christensen
tagline:          ''
description:      'Software Engineer'
url:              http://benjchristensen.com
baseurl:          /

author:
  name:           'Ben Christensen'
  url:            https://twitter.com/benjchristensen

# pagination
gems: [jekyll-paginate]
paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
