# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ben Christensen
tagline:          ''
description:      'Software Engineer'
url:              http://benjchristensen.com
baseurl:          /

author:
  name:           'Ben Christensen'
  url:            https://twitter.com/benjchristensen

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
